apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "miramira"
  MYSQL_DATABASE: "realtime"
  MYSQL_USER: "laravel"
  MYSQL_PASSWORD: "secret"
