apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: default
type: Opaque
stringData:
  APP_KEY: "base64:your-generated-key-here"
  DB_USERNAME: "laravel"
  DB_PASSWORD: "secret"
  REDIS_PASSWORD: ""
  REVERB_APP_KEY: "z6jspkek2dzh9a3vnlig"
  REVERB_APP_SECRET: "eamhhmv3nenrke26giqs"
  VITE_REVERB_APP_KEY: "${REVERB_APP_KEY}"
  MAIL_USERNAME: "mehdizagmouzi2019@gmail.com"
  MAIL_PASSWORD: "awtvbfpaxfaejcyd"
  MAIL_FROM_ADDRESS: "mehdizagmouzi2019@gmail.com"
  GOOGLE_CLIENT_ID: "652498434791-0s0s23ecc0lddbu9agdgmulat1ln96hd.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "652498434791-0s0s23ecc0lddbu9agdgmulat1ln96hd.apps.googleusercontent.com"
  GOOGLE_REDIRECT_URI: "http://<WORKER_PUBLIC_IP>:30080/api/auth/google/callback"